#version 450

struct OctreeNode {
    bool is_leaf;
};

layout (set = 0, binding = 0, std430) restrict readonly buffer WorldData {
    OctreeNode nodes[];
} world_data;

layout (set = 0, binding = 1, rgba8) uniform writeonly image2D outputImage;

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
void main() {
    vec4 pixel = vec4(1, 0, 0, 1);
    imageStore(outputImage, ivec2(gl_GlobalInvocationID.xy), pixel);
}