[package]
name = "renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
render-api = { path = "../render-api" }
ash = "0.38.0"
glfw = { version = "0.58.0", features = ["vulkan"] }
shader = { path = "../shader" }
world = { path = "../world" }
