[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
linalg = { path = "../linalg" }
window = { path = "../window" }
engine = { path = "../engine" }
renderer = { path = "../renderer" }
world = { path = "../world"}
